### ISSUE TITLE
Discord invite expired or invalid

### ISSUE THREAD

**Issue by Michel-0** [buttplugio/buttplug-faq#2]
Hi,
for some reason I'm not able to join https://discord.buttplug.io/.

I tried to join on my mobile as well as on PC.
Discord desktop client, mobile app or web version even with different browsers, nothing works.

Any ideas why this might be the case?
I already tried to join couple of weeks ago - it's still the same.
![Screenshot_20220907-060555](https://user-images.githubusercontent.com/42518412/188786440-18bc5dc4-3735-43ac-b385-97203bb43201.png)

Looking forward for beeing able to join,
kind regards,
me

**Comment by qdot** [comment]
No *clue* why this keeps happening, some people can get in fine, others can't. Try https://discord.gg/QtUQpG3.

**Comment by Michel-0** [comment]
Wow, that was a fast reply...
However i tried 
> https://discord.gg/QtUQpG3

Without avail.
Still says invalid or expired.
I tried on the mobile app, i could try on PC later as well, but i doubt it will be different on PC.

I do have a correct mail adress and phone number verified on my discord, but 2-factor authentication disabled.
Are there any requirements regarding that?
You can set a required verification status in your discord server settings...

**Comment by qdot** [comment]
Nope, we're just set to low security, which requires email verification and that's it. Hmm.

**Comment by Michel-0** [comment]
If you look into the list of invitations in your server settings QtUQpG3 is listed as active and not expired?

Should I contact the discord support?

EDIT: I created a ticket at https://support.discord.com

**Comment by Michel-0** [comment]
Hi again,
discord support replied and confirmed the link is valid.

They suggested to try and check following things:
- **Could you plese clear all bans in `server settings` > `Bans`?**
Because of IP bans it's possible that I get banned IPs.
I get a new IP daily from my internet service provider.
- **Could you please check the members list of your server if there is a `Michel_0` (`Michel_0#4992`)?**
If so (*however that might happened*) please kick / delete it, so I can join *again*.
- **Do you use moderation bot /-s?**
If so which ones (or is this information classified as security-related server secret)?
I might be for some reason on a banlist of a bot (altough I never have been banned from any server).
However If you got moderation bots I / we / you should check their banlist and maybe they have other criteria for users to let them join.

Those are the 3 `most possible` options.
I think especially the last one might be the case... maybe some bot blocks non-static IPs or whatever...?

*The reply of discord support in original:*
> Hey Michael,
 Oh, I see. I've checked the invite link in our system and can confirm the link is valid. If it is still showing up as invalid on your end, it's likely that your IP address is banned from the server. Could you once again ask one of the moderators to clear all bans in Server Settings > Bans? Restart the client afterward.
Keep in mind that if you have an IP address that was used at any point by a user who was banned, you might be banned because of that.
Also, if you were a member of the server in the past, it is possible that a "ghost" version of your account is still a member. This will prevent you from joining again. Have the mods check their user list to make sure your Discord Tag isn't on it. If it is, and you're not on the server, it could be that you weren't fully kicked originally. Once your "ghost" is kicked, you should be able to join again.
Another option is that a moderation bot has your Discord Tag on its blacklist. You can ask the mods to check each bot's blacklist to ensure that your Discord Tag is not on it.
I hope this information helps, but if you still can't get in, let me know!
Cheers,
Lyndl

I think there is a chance we figure this out.
Since you said others have this problem as well I hope you want to find out, too.

Kind regards,
Michel-0

EDIT: btw I did let them Check `QtUQpG3`.

**Comment by Michel-0** [comment]
I didn't do anything meanwhile and tried again yesterday.
`https://discord.com/invite/t9g9RuD` did work out now for some reason.
